### PR TITLE
Cleanup 9.3 branch (pom.versions, plugin version, convert projects)

### PR DESCRIPTION
**Pull request by weissreto**
Streamline all pom.xml versions to 9.3.0-SNAPSHOT
Use project build plugin version 9.3.1
Convert projects to latest 9.3 version

### CODE REVIEW

**Comment by weissreto** [comment]
@ivy-lli Seems the scripts to raise the versions do not work for all and every pom.xml. Can we have a look at them later?

**Comment by ivy-lli** [comment]
Not every project in here is still builded (and may not working) so it's just updating the version which are builded...

**Comment by ivy-lli** [comment]
We always used the latest SNAPSHOT version of the build plugin in this repo...

**Comment by weissreto** [comment]
> We always used the latest SNAPSHOT version of the build plugin in this repo...

This is the 9.3 branch. That is why I use the 9.3 plugin version. Such that the documentation is in synch with this branch.

**Comment by ivy-lli** [comment]
Sorry didn't see that this is merged to 9.3

**Review by ivy-lli — APPROVED** [review]

**Pull request closed without merging**
