### PR TITLE
Cleanup pom.xml, project-build-plugin and ivy project versions

### PR DESCRIPTION
**Pull request by weissreto**
- Cleanup pom.xml files: Tab to spaces. Remove unnecessary entries
- Streamline all pom.xml versions to 9.4.0-SNAPSHOT
- Streamline all project-build-plugin versions to 9.4.0-SNAPSHOT
- Include all sub projects into global reactor
- Convert all projects to latest 9.4

- Do not set test.engine.url in Jenkinsfile explicit so that the url of
the current test engine is used.
- Use latest web-tester version so that we do not have to configure
ivy.test.engine explicit and it works with remote selenium driver

- Modify raise-version.sh so that all pom.xml versions are raised
whether it is a child, parent or reactor POM. Ensure all references are
updated too.

- Modify raise-build-plugin-version.sh so that the project-build-plugin
version is raised in all POMs where it is referenced.

### CODE REVIEW

**Comment by weissreto** [comment]
Finally the build runs the the *.sh do what I like them to do.

**Comment by ivy-rew** [comment]
The Descriptions sounds good: the changeset is too large to review. 
I think having the project-conversion changes in a commit would have helped a lot, to make the change easier to digest.

**Review by ivy-rew — APPROVED** [review]

**Comment by weissreto** [comment]
Yes I know it is too large. Was not expecting that I need that much time and commits to bring that thing to run. 
However, you can simple review Jenkinsfile, *.pom, *.sh scripts. That are the most important changes.

**Comment by ivy-rew** [comment]
I've re-craft this change into 2 distinct commits: https://github.com/axonivy/project-build-examples/pull/64

**Pull request closed without merging**
